# =============================================================================
# OAuth Configuration — generated by OAuth Plugger
# =============================================================================
# NEVER commit this file. It should be in .gitignore.
# =============================================================================

# --- NextAuth Base Config ---
# Generate secret: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
NEXTAUTH_SECRET=
NEXTAUTH_URL=http://localhost:3000
