// Auto-generated by OAuth Plugger — https://github.com/Crackedcoder5TH/REMEMBRANCE-API-Key-Plugger
// Providers: {{PROVIDERS}}

import NextAuth from "next-auth";
{{IMPORTS}}

const handler = NextAuth({
  providers: [
{{CONFIGS}}
  ],
  pages: {
    signIn: "/login",
  },
  callbacks: {
    async session({ session, token }) {
      if (session.user) {
        (session.user as Record<string, unknown>).id = token.sub;
      }
      return session;
    },
  },
  secret: process.env.NEXTAUTH_SECRET,
});

export { handler as GET, handler as POST };
